export const aiTemplates = {
    "default": {
        "title": "New Project (AI Generated)",
        "description": "A skeleton project structure generated by AI.",
        "startDate": "2024-02-01",
        "endDate": "2024-02-28",
        "status": "Planning",
        "tasks": [
            {
                "id": "t_ai_def_1",
                "title": "Phase 1: Planning",
                "type": "Epic",
                "status": "Pending",
                "subtasks": [
                    {
                        "id": "t_ai_def_1_1",
                        "title": "Requirement Gathering",
                        "type": "Task",
                        "status": "Pending"
                    }
                ]
            },
            {
                "id": "t_ai_def_2",
                "title": "Phase 2: Execution",
                "type": "Epic",
                "status": "Pending",
                "subtasks": []
            }
        ]
    }
};
