export const aiTemplates = {
    "default": {
        "title": "New Project (AI Generated)",
        "description": "A comprehensive project structure generated by AI to kickstart your workflow.",
        "startDate": new Date().toISOString().split('T')[0],
        "endDate": new Date(new Date().setDate(new Date().getDate() + 30)).toISOString().split('T')[0],
        "status": "Planning",
        "tasks": [
            {
                "id": "t_ai_def_1",
                "title": "Phase 1: Discovery & Planning",
                "type": "Epic",
                "status": "Pending",
                "startDate": new Date().toISOString().split('T')[0],
                "endDate": new Date(new Date().setDate(new Date().getDate() + 7)).toISOString().split('T')[0],
                "subtasks": [
                    {
                        "id": "t_ai_def_1_1",
                        "title": "Gather Stakeholder Requirements",
                        "type": "Task",
                        "status": "Pending"
                    },
                    {
                        "id": "t_ai_def_1_2",
                        "title": "Define Technical Stacks",
                        "type": "Task",
                        "status": "Pending"
                    }
                ]
            },
            {
                "id": "t_ai_def_2",
                "title": "Phase 2: Development",
                "type": "Epic",
                "status": "Pending",
                "startDate": new Date(new Date().setDate(new Date().getDate() + 8)).toISOString().split('T')[0],
                "endDate": new Date(new Date().setDate(new Date().getDate() + 21)).toISOString().split('T')[0],
                "subtasks": [
                    {
                        "id": "t_ai_def_2_1",
                        "title": "Setup Core Infrastructure",
                        "type": "Task",
                        "status": "Pending"
                    },
                    {
                        "id": "t_ai_def_2_2",
                        "title": "Implement User Authentication",
                        "type": "Task",
                        "status": "Pending"
                    },
                    {
                        "id": "t_ai_def_2_3",
                        "title": "Develop Dashboard UI",
                        "type": "Task",
                        "status": "Pending"
                    }
                ]
            },
            {
                "id": "t_ai_def_3",
                "title": "Phase 3: QA & Deployment",
                "type": "Epic",
                "status": "Pending",
                "startDate": new Date(new Date().setDate(new Date().getDate() + 22)).toISOString().split('T')[0],
                "endDate": new Date(new Date().setDate(new Date().getDate() + 30)).toISOString().split('T')[0],
                "subtasks": [
                    {
                        "id": "t_ai_def_3_1",
                        "title": "Perform Unit & Integration Testing",
                        "type": "Task",
                        "status": "Pending"
                    },
                    {
                        "id": "t_ai_def_3_2",
                        "title": "Final Production Deployment",
                        "type": "Task",
                        "status": "Pending"
                    }
                ]
            }
        ]
    }
};
